# Este é workflow básico com Node e Cypress

name: CI_cy_lab

# Controla quando a ação será executada
on:
  # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch principal (Master)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite que você execute este fluxo de trabalho manualmente na guia "Actions"
  workflow_dispatch:

# workflow composto por uma ou mais tarefas que podem ser executadas sequencialmente ou em paralelo
jobs:
  # Workflow com um Job simples
  build:
    # Máquina escolhida para rodar os testes
    runs-on: ubuntu-latest

    #  Sequência de tarefas que serão executadas como parte de um job
    steps:
      # Verifica o repositório: $GITHUB_WORKSPACE, para que seu job pode acessá-lo
      - uses: actions/checkout@v2

      # Passos para preparar o ambiente e a execução
      - name: Instalando o node
        run: npm install 

      - name: Executando o cypress
        run: npx cypress run
          echo rodando os testes cypress

